  - name: transfer sql statement to remonte
    template:
     src: ../template/config_mysql_group_replication.sql
     dest: /tmp/config_mysql_group_replication.sql

  - name: config mysql group replication
    shell: mysql -hlocalhost -uroot -p{{ mysql_root_password }} -S /tmp/mysql.sock  < /tmp/config_mysql_group_replication.sql

  - name: remove temp file /tmp/config_mysql_group_replication.sql
    file:
     dest: /tmp/config_mysql_group_replication.sql
     state: absent