---
 #导出PATH环境变量
 - name: export path JAVA_HOME variable
   lineinfile:
    path: /etc/profile
    line: JAVA_HOME=/usr/local/jdk1.8.0_171
    insertafter: EOF

 - name: export path JRE_HOME variable
   lineinfile:
    path: /etc/profile
    line: JRE_HOME=/usr/local/jdk1.8.0_171/jre
    insertafter: EOF
    
 - name: export path CLASSPATH variable
   lineinfile:
    path: /etc/profile
    line: export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
    insertafter: EOF
 
 - name: export path PATH variable
   lineinfile:
    path: /etc/profile
    line: export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH
    insertafter: EOF

