---
#由本地传输java安装包到目标主机、并把安装包解压到/usr/local/目录
#等价bash
#scp jdk-xxx.tar.gz 192.168.xx.xx:/tmp/
#tar -xvf /tmp/jdk-xxx.tar.gz -C /usr/local/
 - name: transfer java install package to remote host and unarchive to /usr/local/
   unarchive:
    src: "{{ java_packages_dir }}/{{ java_package }}"
    dest: /usr/local/
    owner: root
    group: root
